### ISSUE TITLE
./PalServer.sh: line 11: run: command not found

### ISSUE THREAD

**Issue by TakiiOS** [s3tupw1zard/palworld-pterodactyl-proton#1]
wine-9.2 (Staging)
:/home/container$ ./PalServer.sh
tid(16) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/container/.steam/steam/logs/stderr.txt'
Logging directory: '/home/container/.steam/steam/logs'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
"@sSteamCmdForcePlatformType" = "windows"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 56.19 (22022100 / 39195172)
 Update state (0x5) verifying install, progress: 22.08 (600312106 / 2718258822)
 Update state (0x5) verifying install, progress: 60.24 (1637353770 / 2718258822)
 Update state (0x0) unknown, progress: 0.00 (0 / 0)
Success! App '2394010' fully installed.
./PalServer.sh: line 11: run: command not found
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by s3tupw1zard** [comment]
Could you post the content of your PalServer.sh file?

**Comment by s3tupw1zard** [comment]
I installed a second instance of the server using this egg.
The script tries to resolve the variables $PROTON and $PALSERVER_EXECUTABLE which should be printed as is into PalServer.sh file without being resolved. The problem is inside the installation container this two variables don’t exist so they‘re resolved to nothing.
I’ll look into this later. There should be a way to mask the two variables inside the echo statement that prints the script.

**Comment by s3tupw1zard** [comment]
Should now be fixed. Please download the new egg json file and update it using that in your panel.

**Comment by TakiiOS** [comment]
Working but impossible to join the server .

**Comment by s3tupw1zard** [comment]
Ah yes. Sorry I didn't add the info that somehow the server runs on the default port instead of the port added in the panel.
I don't know why it ignores the port that's added to the server.

So you would need to connect using the default port.

**Comment by TakiiOS** [comment]
You go look for fix it ?

**Comment by s3tupw1zard** [comment]
Yes, I'll look into it

**Comment by s3tupw1zard** [comment]
I fixed it in issue #2
